import { EventEmitter } from 'events';

class AppEventBus extends EventEmitter {}

export const eventBus = new AppEventBus();

// Core Domain Event Types
export const DomainEvents = {
  ATTENDANCE_CLOCKED_IN: 'ATTENDANCE_CLOCKED_IN',
  ATTENDANCE_LATE_DETECTED: 'ATTENDANCE_LATE_DETECTED',
  ATTENDANCE_CLOCKED_OUT: 'ATTENDANCE_CLOCKED_OUT',
  LEAVE_APPLIED: 'LEAVE_APPLIED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STATUS_UPDATED: 'TASK_STATUS_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  BROADCAST_PUBLISHED: 'BROADCAST_PUBLISHED'
};
